### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by OrtheSnowJames** [TeamMidnightDust/BlinkingSkinPort#1]
Whenever I use fabric, It crashes. But if I use Forge it doesn't crash but it won't identify the mod. Is there a new version?
I only used: fabric-API-0.34.2+1.16 and blinkingskinport-2.0.0.

**Comment by Motschen** [comment]
You need to install [AutoConfig](https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api) and [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
This will be changed in the future to make it more clear.
