### ISSUE TITLE
Crashing in 1.19.3

### ISSUE THREAD

**Issue by MutatedNut** [TeamMidnightDust/BlinkingSkinPort#4]
Every time I click the options button my game crashes. This only occurs in 1.19.3. I have the Cloth Config mod as well but it doesn't make a difference.

**Comment by Motschen** [comment]
Install the latest version of MidnightLib: https://modrinth.com/mod/midnightlib

**Comment by MutatedNut** [comment]
> Install the latest version of MidnightLib: https://modrinth.com/mod/midnightlib

That fixed it, thank you.
